---
title: "Intro to Programming for Data Science"
format: 
  revealjs:
    theme: dark
editor: visual
---

## Setup {.smaller}

| Software                  | Download URL                                                                                                                              |
|---------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| R                         | [The Comprehensive R Archive Network (r-project.org)](https://cloud.r-project.org/)                                                       |
| Rtools                    | [RTools: Toolchains for building R and R packages from source on Windows (r-project.org)](https://cran.r-project.org/bin/windows/Rtools/) |
| RStudio                   | [Download the RStudio IDE - RStudio](https://www.rstudio.com/products/rstudio/download/)                                                  |
| Python                    | [Download Python \| Python.org](https://www.python.org/downloads/)                                                                        |
| Anaconda                  | [Anaconda \| Anaconda Distribution](https://www.anaconda.com/products/distribution)                                                       |
| Quarto                    | [Quarto - Get Started](https://quarto.org/docs/get-started/)                                                                              |
| VS Code                   | [Download Visual Studio Code - Mac, Linux, Windows](https://code.visualstudio.com/Download)                                               |
| Git                       | [Git - Downloads (git-scm.com)](https://git-scm.com/downloads)                                                                            |
| GitHub Desktop (optional) | [GitHub Desktop \| Simple collaboration from your desktop](https://desktop.github.com/)                                                   |

**Passion to Grow**

## Getting Git to Work

[Group GitHub Repository](https://github.com/geshun/analytics-group)

. . .

Cloning (or Downloading) the Repository

. . .

Opening the presentation

. . .

Opening the Jupyter notebook (`.ipynb`) or Quarto (`.qmd`)

## Areas of Focus

-   **Tool and Platform**: *Python, R, AWS, Docker, SQL*

-   **Methodology**: *Regression, Classification*

-   **Thinking Process**: *Framing analytical questions*

-   **Project Management**: *Agile Framework - Jira, Version control, Documentation*

## Method of Thought

::: columns
::: {.fragment .fade-in}
> Analysis *reveals a pattern - how it works (knowledge)*
:::

::: {.fragment .fade-in}
> Synthesis *reveals understanding - why it works the way it does*
:::
:::

## Analytic Problem

> In the past 5 year, $KN^3$ company recorded the following revenue: `12000, 23000, 15000, 10000, 18000`. How do you help $KN^3$ understand if it's 2022 revenue will be in line with recent revenues?

## Recap {.smaller}

1.  Data or values have types and can be reduced to the built in types - thus built in types are the indivisible types, helping us build all other types
2.  Be mindful of the (properties of) data structure you choose sinces that affects the type of computation you can do with the data and the efficiency you can get
3.  On methodology, we realized there are alternatives to arithmetic mean and we now understand why we look at the mean
4.  With regards to code management, we connected or cloned a git hub repo
5.  Appreciated how the reductionist approach helps in thinking through a problem and help us write modular code - thus (standalone) code that work independently.
